-- MySQL Script generated by MySQL Workbench
-- Mon Nov 15 22:48:51 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema course_booking
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema course_booking
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `course_booking` DEFAULT CHARACTER SET utf8 ;
USE `course_booking` ;

-- -----------------------------------------------------
-- Table `course_booking`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course_booking`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(100) NOT NULL,
  `last_name` VARCHAR(100) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `is_admin` TINYINT(1) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course_booking`.`courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course_booking`.`courses` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(1000) NOT NULL,
  `price` DECIMAL(8,2) NOT NULL,
  `is_active` TINYINT(1) NOT NULL DEFAULT 1,
  `datetime_created` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `course_booking`.`course_enrollments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `course_booking`.`course_enrollments` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `course_id` INT UNSIGNED NOT NULL,
  `user_id` INT UNSIGNED NOT NULL,
  `datetime_enrolled` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`, `course_id`, `user_id`),
  INDEX `fk_course_enrollments_courses_idx` (`course_id` ASC),
  INDEX `fk_course_enrollments_users1_idx` (`user_id` ASC),
  CONSTRAINT `fk_course_enrollments_courses`
    FOREIGN KEY (`course_id`)
    REFERENCES `course_booking`.`courses` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_course_enrollments_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `course_booking`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;